In [ ]:
import pandas as pd

from sklearn.cluster import KMeans

In [ ]:
df = pd.read_csv('clustering.csv')

In [ ]:
df

,Unnamed: 0,Terrestrial,Sea,Percentage,Population,Per Capita,Total
0,Texas,18893.000,148.250000,0.170413,1380.348615,94.926049,131031.04030
1,Hawaii,16.638,190.250000,0.118071,956.378878,94.926049,90785.26826
2,Western Australia,7000.000,63.166667,0.068250,552.822097,98.485776,54445.11319
3,United States,28440.000,450.000000,0.397222,3217.495447,94.926049,305424.13040
4,United Kingdom,23000.000,70.000000,0.138935,1125.373912,98.247744,110565.44800
5,Australia,8156.000,112.250000,0.103494,838.304058,98.485776,82561.02564
6,China,5000.000,33.800000,0.041729,338.005841,108.368100,36629.05077
7,Brazil,8515.000,42.500000,0.061723,499.955220,69.522244,34758.00883
8,Soviet Union,8000.000,7.500000,0.037875,306.790643,92.717641,28444.90470
9,India,3287.000,35.000000,0.035359,286.411372,58.125376,16647.76866
10,Canada,3500.000,5.000000,0.017637,142.855935,99.042304,14148.78096

In [ ]:
# Method 1

# Initialize KMeans
kmeans = KMeans(n_clusters=3)  # You can choose the number of clusters

# Fitting the input data
kmeans = kmeans.fit(df.iloc[:,1:])

# Getting the cluster labels
labels = kmeans.predict(df.iloc[:,1:])

# Adding labels to the original DataFrame
df['Cluster'] = labels

print(df.iloc[:,[0,-1]])

           Unnamed: 0  Cluster
0               Texas        2
1              Hawaii        2
2   Western Australia        0
3       United States        1
4      United Kingdom        2
5           Australia        2
6               China        0
7              Brazil        0
8        Soviet Union        0
9               India        0
10             Canada        0

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

In [ ]:
# Data for method 2
df2 = df

In [ ]:
# Method 2
from sklearn.preprocessing import StandardScaler

# Initialize KMeans
kmeans = KMeans(n_clusters=3)  # You can choose the number of clusters

# Normalize the data
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df.iloc[:,1:])

# Fitting the input data
kmeans = kmeans.fit(df_scaled)

# Getting the cluster labels
labels = kmeans.predict(df_scaled)

# Adding labels to the original DataFrame
df['Cluster'] = labels

print(df.iloc[:,[0,-1]])

           Unnamed: 0  Cluster
0               Texas        0
1              Hawaii        0
2   Western Australia        2
3       United States        1
4      United Kingdom        0
5           Australia        0
6               China        2
7              Brazil        0
8        Soviet Union        2
9               India        0
10             Canada        2

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(